source_db:
  user: source_user
  password: source_pass
  dsn: source_host:1521/sourcedb
target_db:
  user: target_user
  password: target_pass
  dsn: target_host:1521/targetdb

max_threads: 4  # Number of threads to use for batch processing

table_config:
  - table_name: "EMPLOYEES"
    schema: "HR"
    primary_key: ["EMPLOYEE_ID"]
    chunk_size: 10000
    exclude_columns: ["LAST_UPDATED"]
  - table_name: "ORDER_ITEMS"
    schema: "SALES"
    primary_key: ["ORDER_ID", "ITEM_ID"]
    chunk_size: 5000
    columns: ["ORDER_ID", "ITEM_ID", "QUANTITY", "PRICE", "STATUS"]
    exclude_columns: ["LAST_UPDATED", "CREATED_BY"]
  - table_name: "TRANSACTIONS"
    schema: "FIN"
    primary_key: ["TRANSACTION_ID"]
    chunk_size: 15000
    where_clause: "TRANSACTION_DATE >= DATE '2024-01-01'"
    exclude_columns: []
  - table_name: "AUDIT_LOG"
    schema: "AUDIT"
    primary_key: ["LOG_ID"]
    chunk_size: 2000
    columns: ["LOG_ID", "USER_ID", "ACTION", "TIMESTAMP", "STATUS"]
    where_clause: "STATUS = 'ACTIVE'"
    exclude_columns: ["LAST_UPDATED"]

paths:
  audit_log: ./logs/audit.log
  source_sql_output: ./output/source_sync_statements.sql
  target_sql_output: ./output/target_sync_statements.sql
  comparison_report: ./output/comparison_report.csv

flags:
  enable_audit_table: true
  enable_reverification: true
  enable_restart: true
  debug: false  # Set to true to enable debug logging 